add provider base for sound definition
ModdingX/LibX pull request #27
Opened 2021-10-09 19:56 UTC by MelanX

2021-10-10 11:47 UTC, noeppi-noeppi requested changes

2021-10-10 11:47 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +    protected void manualSound(SoundEvent soundEvent) {
There is only one sound json, so you don't do that sound *manually*. Maybe this should be renamed to something like `ignore`

2021-10-10 11:47 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +    protected Sounds sound(ResourceLocation name, SoundDefinition.SoundType type, int amount) {
Should add the sound to the blacklist, so it is not passed to `defaultSoundDefinition` if used in `setup`.

2021-10-10 11:47 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +    protected Sounds sound(String name, int amount) {
What if sound files have a different naming scheme?

2021-10-10 11:47 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +    protected static class Sounds extends ArrayList<SoundDefinition.Sound> {
Please encapsulate the list.

2021-10-10 11:47 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public Sounds volume(double volume) {
JavaDoc for all the methods in this class missing. What is `volume`, what range should it be?

2021-10-10 11:47 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public SoundDefinition asDefinition() {
Do people need to manually call this? If no, make it `private`. If yes, make it, so it's not required.

2021-10-11 10:54 UTC, MelanX commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public Sounds volume(double volume) {
Should I refer to the vanilla methods with their Javadoc in all the places or write the exact same thing on "my" methods? I ask because you didn't say it's wrong in `Sounds#streamSounds`.

2021-10-11 10:56 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public Sounds volume(double volume) {
These are forge methods not vanilla methods. But it should be fine to refer to them if you can't give better docs.

2021-10-11 11:01 UTC, MelanX commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public SoundDefinition asDefinition() {
They have to call it manually. And they have to call it because I don't know at which other method I should return the SoundDefinition because it's like a builder. After you setup everything, you still have to call `build()`. Here it's called `asDefinition()`.

2021-10-11 11:01 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public SoundDefinition asDefinition() {
Then store the objects in a list and after calling setup, when processing the sounds, build them.

2021-10-11 11:12 UTC, MelanX commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public SoundDefinition asDefinition() {
If I call it after the setup, the user can't set a subtitle for the definition or set replace to true (to overwrite existing definitions).

2021-10-11 11:13 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public SoundDefinition asDefinition() {
Uhhm... You set subtitles in `setup`, right? So why not?

2021-10-11 11:14 UTC, MelanX commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public SoundDefinition asDefinition() {
But I need the SoundDefinition object to set the subtitle. For that, I have to transform the list of Sounds to a SoundDefinition.

2021-10-11 11:15 UTC, noeppi-noeppi commented on src/main/java/io/github/noeppi_noeppi/libx/data/provider/SoundDefinitionsProviderBase.java
> +        public SoundDefinition asDefinition() {
Store an empty sound definition internally, expose its methods (except `with`) and then after setup, merge the sounds int that definition?

2021-10-11 11:30 UTC, MelanX commented
I added a new method which transforms the location. You can override this if your file names follow another pattern.

2021-10-14 14:50 UTC, noeppi-noeppi approved these changes

2021-10-15 08:57 UTC, merged